[2025-06-01T15:09:41.984+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: evaluate_and_train.train_model manual__2025-06-01T15:09:30.936917+00:00 [queued]>
[2025-06-01T15:09:42.008+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: evaluate_and_train.train_model manual__2025-06-01T15:09:30.936917+00:00 [queued]>
[2025-06-01T15:09:42.010+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-01T15:09:42.049+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2025-06-01 15:09:30.936917+00:00
[2025-06-01T15:09:42.099+0000] {standard_task_runner.py:60} INFO - Started process 29421 to run task
[2025-06-01T15:09:42.120+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'evaluate_and_train', 'train_model', 'manual__2025-06-01T15:09:30.936917+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/evaluate_and_train.py', '--cfg-path', '/tmp/tmp40knmxq0']
[2025-06-01T15:09:42.129+0000] {standard_task_runner.py:88} INFO - Job 103: Subtask train_model
[2025-06-01T15:09:42.316+0000] {task_command.py:423} INFO - Running <TaskInstance: evaluate_and_train.train_model manual__2025-06-01T15:09:30.936917+00:00 [running]> on host 9c020e596300
[2025-06-01T15:09:42.685+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='evaluate_and_train' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T15:09:30.936917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T15:09:30.936917+00:00'
[2025-06-01T15:09:44.483+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:09:44 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-01T15:09:49.542+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:09:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-01T15:09:49.791+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-06-01T15:09:50.141+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'BestHousePriceModel'.
[2025-06-01T15:09:50.229+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:09:50 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: BestHousePriceModel, version 1
[2025-06-01T15:09:50.229+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'BestHousePriceModel'.
[2025-06-01T15:09:50.316+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:09:50 INFO mlflow.tracking._tracking_service.client: üèÉ View run smiling-duck-60 at: http://172.17.0.1:30500/#/experiments/1/runs/c86ce479c9c441cd922ffce20ca1be77.
[2025-06-01T15:09:50.316+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:09:50 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://172.17.0.1:30500/#/experiments/1.
[2025-06-01T15:09:50.419+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-01T15:09:50.440+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=evaluate_and_train, task_id=train_model, execution_date=20250601T150930, start_date=20250601T150941, end_date=20250601T150950
[2025-06-01T15:09:50.554+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-01T15:09:50.603+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
